### ISSUE TITLE
v1 tag missing from Docker hub

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#3]
### What I did:

Followed the example in README:

```
      - name: Publish
        uses: docker://solvaholic/octodns-action:v1
        with:
          args: public.yaml --doit
```

### What I expected to happen:

Use the most recent v1.x.x image, from Docker hub.

### What happened instead:

Couldn't pull the image because that tag didn't exist.

### Additional info:

I manually pushed a v1 tag from the 1.1.0 image.

- [x] Update [housekeeping](https://github.com/solvaholic/octodns-action/blob/master/.github/workflows/housekeeping.yml) to bump the major version tag on Docker hub, like it does for GitHub's package registry.
- [x] Make sure that actually works.
