### ISSUE TITLE
The v99 release breaks dependabot updates

### ISSUE THREAD

**Issue by xt0rted** [solvaholic/octodns-sync#34]
### What I did

Added this action to my workflow using the latest version like so: `solvaholic/octodns-sync@v2.1.2`

I also have dependabot setup to keep my actions up to date so I can review the changes for each release.

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
```

### What I expected to happen

Nothing.

### What happened instead

Dependabot opened a PR bumping the version from [`v2.1.2`](https://github.com/solvaholic/octodns-sync/releases/tag/v2.1.2) to [`v99`](https://github.com/solvaholic/octodns-sync/releases/tag/v99).

![image](https://user-images.githubusercontent.com/831974/104063368-0ee40400-51ca-11eb-8667-bc7bdc6ed5c7.png)
