### ISSUE TITLE
[2.2.x] Running octodns-sync twice in one job fails

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#57]
ℹ️ This issue does not affect solvaholic/octodns-sync@v2.1.x ℹ️ 

## Description

Running octodns-sync (this Action) multiple times in one job fails when `scripts/install.sh` tries to clone **octodns/octodns** again to an existing `octodns-src` directory.

## Expected Behavior

Multiple runs of octodns-sync in one job should not block each other. For example, you may have a `public.yaml` and a `private.yaml` and want to test both in one job.

## Actual Behavior

The first time I tried it, both runs seemed to succeed OK 🤷 

The next time, the first step succeeded and the repeat step failed because Git refused to re-use the `octodns-src` directory.

## Possible Fix

Teach `scripts/install.sh` to recognize and use an existing clone.

## Steps to Reproduce

```yaml
      # Run octodns to test current config
      - name: Test current configuration
        id: octodns-test
        uses: solvaholic/octodns-sync@issue50
        with:
          config_path: public.yaml
          doit: 'no'
          add_pr_comment: 'Yes'
          octodns_ref: ${{ steps.pick-ref.outputs.octodns_ref }}
          pr_comment_token: ${{ github.token }}
      # Test again in the same job, to see what happens
      - name: Test current configuration again
        id: octodns-test2
        uses: solvaholic/octodns-sync@issue50
        with:
          config_path: public.yaml
          doit: 'no'
          add_pr_comment: 'Yes'
          octodns_ref: ${{ steps.pick-ref.outputs.octodns_ref }}
          pr_comment_token: ${{ github.token }}
```

## Your Environment

* Version used: 7fa64b62d9ed63618999d8b8b68cbee1916950c9
* Link to your project: n/a

**Comment by solvaholic** [comment]
> The first time I tried it, both runs seemed to succeed OK 🤷

I see it! On the first run I had `octodns_ref` set to `v0.9.12`, which caused `scripts/install.sh` to use `pip install` rather than cloning the repo.

https://github.com/solvaholic/octodns-sync/blob/7fa64b62d9ed63618999d8b8b68cbee1916950c9/scripts/install.sh#L6-L18

For the next test I made `octodns_ref` a branch name, `master`, which caused `scripts/install.sh` to try to re-clone the repo in the second step.

A proper solution should account for this scenario as well:

```yaml
      # Run octodns to test the first time, with a branch name
      - name: Test current configuration
        id: octodns-test
        uses: solvaholic/octodns-sync@7fa64b6
        with:
          octodns_ref: master
      # Test again in the same job, with a version tag
      - name: Test current configuration again
        id: octodns-test2
        uses: solvaholic/octodns-sync@7fa64b6
        with:
          octodns_ref: v0.9.12
      # Test again in the same job, with a different branch name
      - name: Test current configuration again again
        id: octodns-test3
        uses: solvaholic/octodns-sync@7fa64b6
        with:
          octodns_ref: super-feature
      # Test again in the same job, with a different version tag
      - name: Test current configuration again again again
        id: octodns-test4
        uses: solvaholic/octodns-sync@7fa64b6
        with:
          octodns_ref: v0.9.11
```

It may suffice to `rm -rf ./octodns-src` at the beginning of `scripts/install.sh`. I think it seems safer, at least in the meantime, to `exit 1` if `command -v octodns-sync` evaluates true. (And output a helpful warning, of course.)

I'd like that (`exit 1` if `octodns-sync` command is already present) as a solution, IF this Action also documents a method to, with one workflow job, run `octodns-sync` on more than one config `.yaml`.
