### ISSUE TITLE
What does "deploy" mean, for this Action?

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#58]
In https://github.com/solvaholic/octodns-sync/issues/41#issuecomment-792223562 @xt0rted explained:

> I'm doing branch deploys, so once the plan looks good in the PR I'm deploying the PR branch, verifying the changes, then merging the PR to `main`. If I need to revert my changes I can do another deploy of the `main` branch and hopefully get back to where I started before the PR was opened.

That approach makes a lot of sense to me _when the repository is code for an application_. Like for GitHub.com, or when the repo is a Docker Compose stack, or any cloud-hosted service, or DNS or other service configurations. You can deploy from any commit to different environments including production. It doesn't matter whether the commit is in `main` or another branch.

**solvaholic/octodns-sync** is a GitHub Action that will run `octodns-sync` from **octodns/octodns** to test and deploy DNS configuration stored in a repository on GitHub.com.

What does "deploy" mean, for this Action? Or, I think, for any GitHub Action?

**Comment by solvaholic** [comment]
Braindumping here as I consider the question. Please comment to share your thoughts as well :bow:

> What does "deploy" mean, for this Action?

Just now I think these things are true related to that question:

- A GitHub Action is [available to use like so](https://docs.github.com/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions), based on any Git ref or commit SHA:

    ```yaml
    # Reference a specific commit
    - uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
    # Reference the major version of a release
    - uses: actions/setup-node@v1
    # Reference a minor version of a release
    - uses: actions/setup-node@v1.2
    # Reference a branch
    - uses: actions/setup-node@main
    ```

- A release in the Action's repository can be [published to the Marketplace](https://docs.github.com/actions/creating-actions/publishing-actions-in-github-marketplace)

From there I think whereas an application may be deployed to, like, test and production environments, every commit pushed to an Action's repository is implicitly deployed, it's always available for use.

So maybe: An Action can be deployed to the Marketplace by ticking that box on a release and publishing it. It can be deployed to `@main` by merging the commit to the **main** branch. And its commits and refs are all implicitly deployed as, say, unreleased versions.

Then, I think, when deploying this Action to `@main` I'd want to ensure:

- Existing/previous usage still works as-expected (no breaking changes)
- Everything, including new features, works as-documented
- The changelog describes significant changes since the latest Marketplace release
- The readme is up-to-date and correct

In addition to those, when deploying to Marketplace I'd want to ensure:

- Release notes and changelog are in sync
- Major and minor version tags correctly point to their latest patch release

And: Since any GitHub user can deploy modifications by opening a pull request (which will be available at the PR head's commit SHA) I'm uninterested in maintaining criteria or requirements for that scenario. There's just "available", "ready for **main**", and "ready for Marketplace".
