### ISSUE TITLE
This Action does not work with extracted providers

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#86]
## Description
Providers are being extracted from octodns/octodns to their own repositories in the octodns org: https://github.com/octodns/octodns/issues/622

Currently, this Action does not work with providers that have already been extracted. That means, for example, this Action cannot be used with octodns/octodns at the default branch.

## Expected Behavior
This Action should Just Work with octodns: If an extracted provider is used in the config, then install it.

## Actual Behavior
If the provider has been installed by other means, this Action continues to function. If not, then an error probably similar to:

```text
2022-01-11T20:48:20  [140712345147200] WARNING Route53 octodns_route53 shimmed. Update your provider class to octodns_route53.Route53Provider. Shim will be removed in 1.0
2022-01-11T20:48:20  [140712345147200] ERROR Route53 Route53Provider has been moved into a seperate module, octodns_route53 is now required. Provider class should be updated to octodns_route53.Route53Provider
```

## Possible Fix
Could detect providers used in config, and install them.
Or install all of the extracted providers.
Or stick with v0.9.14 forever.

## Steps to Reproduce

1. Configure octodns to use an extracted provider
1. Configure workflow to run this action with **octodns_ref** set to "master"
1. Run that workflow

## Context
Can't use the latest octodns/octodns with this Action.

[This workflow definition](https://github.com/solvahol/dns/blob/c1ecc399dc8bc323f50eac5637481565fb2e7332/.github/workflows/octodns-validate.yml#L94-L100) failed because I didn't install octodns_route53:

```yaml
      - name: Run `octodns-sync` with ${{ needs.meta.outputs.config }}
        id: octodns-sync
        uses: solvaholic/octodns-sync@main
        with:
          config_path: ${{ needs.meta.outputs.config }}
          octodns_ref: master
```

[This workflow definition](https://github.com/solvahol/dns/blob/1c6087545e966fdc2214b9b71174383393eb4679/.github/workflows/octodns-validate.yml#L94-L100) ran successfully:

```yaml
      - name: Run `octodns-sync` with ${{ needs.meta.outputs.config }}
        id: octodns-sync
        uses: solvaholic/octodns-sync@main
        with:
          config_path: ${{ needs.meta.outputs.config }}
          octodns_ref: v0.9.14
```

## Your Environment

* Version used: solvaholic/octonds-sync@main, octodns/octodns at master
* Link to your project: https://github.com/solvahol/dns
